base:
  is_R50: 1
  is_SAMVIT: 0
  dataset_name: brain
  gpu_id: '3'
  original_checkpoint: 'lvm-med-resnet' 
  best_valid_model_checkpoint: './working_dir/checkpoint/'
  frozen_eval: 0
  model: '1-fcn'
  test_mode: 'best_valid'
  valid_rate: 0.3
  
train:
  train_batch_size: 64
  valid_batch_size: 1
  test_batch_size: 1
  learning_rate: 0.0005
  num_epochs: 30
  linear_eval: 0
  solver: 'adam'

dataloader:
  data_path: './dataset_demo/BRAIN'
  