base:
  is_2D: 1
  is_3D: 0
  is_R50: 1
  is_SAMVIT: 0
  dataset_name: buidnewprocess
  gpu_id: '5'
  original_checkpoint: 'lvm-med-resnet' # change checkpoints here
  best_valid_model_checkpoint: './working_dir/checkpoint/BUID_R50'
  image_shape: 256

train:
  train_batch_size: 8
  valid_batch_size: 1
  test_batch_size: 1
  optimizer: 'adam'
  learning_rate: 0.0001
  num_epochs: 50
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0
  scheduler: 0

dataloader:
  train_dir_img: './dataset_demo/BUID/train'
  train_dir_mask: './dataset_demo/BUID/train_labels'
  valid_dir_img: './dataset_demo/BUID/valid'
  valid_dir_mask: './dataset_demo/BUID/valid_labels'
  test_dir_img: './dataset_demo/BUID/test'
  test_dir_mask: './dataset_demo/BUID/test_labels'
  have_label: './dataset_demo/BUID/have_label.txt'
  non_label: './dataset_demo/BUID/non_label.txt'
