base:
  is_2D: True
  is_3D: False
  dataset_name: buidnewprocess
  random_seed: 100
  gpu_id: 3
  num_workers: 40
  pin_memory: True 
  original_checkpoint: './working_dir/sam_vit_b_01ec64.pth' # Original checkpoint from segment-anything project
  best_valid_model_checkpoint: 'lvm_med_sam_model_best_dice_original_buidnewprocess_seed' # I just change the path to save model here
  image_shape: (3, 1024)

train:
  task: sam
  train_batch_size: 20
  valid_batch_size: 1
  test_batch_size: 1
  optimizer: 'adam'
  learning_rate: 1e-4
  num_epochs: 20

dataloader:
  train_dir_img: './dataset_demo/BUID/train'
  train_dir_mask: './dataset_demo/BUID/train_labels'
  valid_dir_img: './dataset_demo/BUID/valid'
  valid_dir_mask: './dataset_demo/BUID/valid_labels'
  test_dir_img: './dataset_demo/BUID/test'
  test_dir_mask: './dataset_demo/BUID/test_labels'