base:
  is_2D: True
  is_3D: False
  dataset_name: kvasir
  random_seed: 100
  gpu_id: 3
  num_workers: 40
  pin_memory: True 
  original_checkpoint: ./working_dir/sam_vit_b_01ec64.pth' # Original checkpoint from segment-anything project
  best_valid_model_checkpoint: 'sam_model_best_dice_original_kvasir_seed'
  image_shape: (3, 1024)

train:
  task: sam
  train_batch_size: 20
  valid_batch_size: 1
  test_batch_size: 1
  optimizer: 'adam'
  learning_rate: 3e-4
  num_epochs: 20

dataloader:
  train_dir_img: './dataset_demo/Kvasir/train'
  train_dir_mask: './dataset_demo/Kvasir/train_labels'
  valid_dir_img: './dataset_demo/Kvasir/valid'
  valid_dir_mask: './dataset_demo/Kvasir/valid_labels'
  test_dir_img: './dataset_demo/Kvasir/test'
  test_dir_mask: './dataset_demo/Kvasir/test_labels'