base:
  is_2D: False
  is_3D: True
  dataset_name: las_mri
  random_seed: 100
  gpu_id: 3
  num_workers: 40
  pin_memory: True 
  original_checkpoint: './working_dir/sam_vit_b_01ec64.pth' # Original checkpoint from segment-anything project
  best_valid_model_checkpoint: 'sam_model_best_original_las_mri_seed'
  image_shape: (3, 1024)

train:
  task: sam
  train_batch_size: 20
  valid_batch_size: 1
  test_batch_size: 1
  optimizer: 'adam'
  learning_rate: 5e-5
  num_epochs: 30

dataloader:
  train_dir_img: './dataset_demo/MMWHS_MR_Heart/train'
  train_dir_mask: './dataset_demo/MMWHS_MR_Heart/train_labels'
  valid_dir_img: './dataset_demo/MMWHS_MR_Heart/valid'
  valid_dir_mask: './dataset_demo/MMWHS_MR_Heart/valid_labels'
  test_dir_img: './dataset_demo/MMWHS_MR_Heart/test'
  test_dir_mask: './dataset_demo/MMWHS_MR_Heart/test_labels'